((magit-branch nil)
 (magit-commit nil)
 (magit-diff
  ("--no-ext-diff" "--stat")
  (("--" "application/service/course_short/ShortResource.php"))
  (("--" "application/user/controller/Activity.php"))
  (("--" "./"))
  (("--" "build.php"))
  (("--" "run.sh")
   "--stat")
  (("--" "application/api/controller/AdminUser.php"))
  (("--" "run.sh"))
  (("--" "run.sh")
   "-U2"))
 (magit-diff:-U "2")
 (magit-dispatch nil)
 (magit-log
  ("-n256" "--graph" "--decorate")
  (("--" "./")))
 (magit-merge nil)
 (magit-pull nil)
 (magit-push nil)
 (magit-stash nil)
 (magit:-- "build.php" ".." ""))
